#!/bin/bash 

echo "--------------------------------------------"
echo "for faster results, disable the Server tests"
echo "--------------------------------------------"

echo "gc-ing" 
rm -rf *~ */*~ ; rm -rf errors.txt 

echo "making"
time raco make Admin/manager.rkt Remote/*.rkt 

echo "testing"
echo "start" > errors.txt
time raco test Common/*.rkt 2>> errors.txt
time raco test Editor/map-editor.rkt
time raco test Player/*.rkt 2>> errors.txt
time raco test Admin/referee.rkt Admin/state.rkt 2>> errors.txt
time raco test Remote/*.rkt 2>> errors.txt
time raco test Server/*.rkt 2>> errors.txt

echo "end" >> errors.txt
 
echo "grepping" 
if grep --quiet "non-zero exit" errors.txt; then 
   cat errors.txt 
else 
   grep location errors.txt
fi
