#!/bin/bash 

for i in 1
do
    echo "--------------------------------- running server test #$i ---------------------------------"
    ./xtest ServerTests ./xclients ./xserver 
done

for i in 1 
do
    echo "--------------------------------- running client test #$i ---------------------------------"
    ./xtest ClientTests ./xclients ./xserver 
done

