#! /bin/sh
#| -*- racket -*-
exec racket -W error -tm "$0" -- ${1+"$@"}
|#
#lang racket

;; main p:port-number (between 10,000 and 60,000) launches a server on this port
;; points n clients there 

(provide main)

;; ---------------------------------------------------------------------------------------------------
(require "run-server-client.rkt")
(require SwDev/Testing/harness)

;; ---------------------------------------------------------------------------------------------------
(test-plain-and-pretty-json?             #f)
(test-fast-and-slow-delivery?            #f)
(test-with-and-without-trailing-newline? #f)
(test-with-and-without-escaped-unicode?  #f)

;; Send all inputs first before looking for output
(test-with-batch-mode?                   #t)

;; Give the server this much time to wait 2 x 20s (see config in `run-server`)
;; and to play the entire tournament. 
(unset-time-out #:limit 90) ;; in s

(define (main path-to-test-directory path-to-xclient path-to-xserver)
  (define tester (client-and-server #:check values))
  [tester path-to-test-directory path-to-xclient path-to-xserver])